- name: Install curl with proxy credentials that contain quotes
  win_chocolatey:
    name: "{{ item.package_name }}"
    params: "{{ item.parameters }}"
    state: present
  with_items: "{{ packageinfo }}"
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

